spring.application.name=TGBotForShelter
bot.token=${TELEGRAM_BOT_TOKEN:}
bot.username=${TELEGRAM_BOT_USERNAME:}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/tgBot
spring.datasource.username=postgres
spring.datasource.password=202054
spring.jpa.show-sql=true

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml
spring.liquibase.enabled=true

telegram.bot.username=eweqwefewfdsdsd_bot
server.port = 8080
spring.profiles.active=
telegram.bot.token=8256037945:AAGFssL8ltH4QVUAy80aqdXH70SABNoyYU0
